services:
  web:
    build: .
    container_name: leo_learning_web
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    env_file:
      - .env
    networks:
      - leo_learning_network

  db:
    image: mysql:8.0
    container_name: leo_learning_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: user
      MYSQL_PASSWORD: user123
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - leo_learning_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: leo_learning_phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      PMA_USER: ${DB_USER}
      PMA_PASSWORD: ${DB_PASS}
    depends_on:
      - db
    networks:
      - leo_learning_network

volumes:
  db_data:

networks:
  leo_learning_network:
    driver: bridge
